twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals : 
            name_boutique : '%name_boutique%'
    #form_themes : ['bootstrap_4_layout.html.twig']
    #form-themes : 
        #- "@FOSCKEditor/form/ckeditor_widget.html.twig"
    
